In [2]:
import cv2
import numpy as np

In [4]:
img=cv2.imread(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\img3.jpg")
cv2.imshow("MEOW",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

RESIZE THE IMG

In [9]:
img=cv2.imread(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\img3.jpg")
re_img=cv2.resize(img,(900,800))
cv2.imshow("MEOW",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
v=np.array([[1,2,1,2],[1,2,1,2]])
v

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [11]:
img=cv2.imread(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\img3.jpg")
print(img)# poore img ke pixels milenge

[[[132 111 136]
  [133 112 137]
  [133 113 136]
  ...
  [185 167 150]
  [186 168 151]
  [187 169 152]]

 [[132 111 136]
  [133 112 137]
  [133 113 136]
  ...
  [185 167 150]
  [186 168 151]
  [187 169 152]]

 [[133 113 136]
  [133 113 136]
  [134 114 137]
  ...
  [186 168 151]
  [187 169 152]
  [189 171 154]]

 ...

 [[112  96  80]
  [111  95  79]
  [110  94  78]
  ...
  [ 78  63  54]
  [ 83  68  59]
  [ 87  72  63]]

 [[112  96  80]
  [111  95  79]
  [110  94  78]
  ...
  [ 95  78  69]
  [ 88  71  62]
  [ 81  64  55]]

 [[112  96  80]
  [111  95  79]
  [110  94  78]
  ...
  [ 83  66  57]
  [ 79  62  53]
  [ 90  73  64]]]


In [16]:
img=cv2.imread(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\img1.jpg")
re_img=cv2.resize(img,(900,800))
#h=np.hstack((re_img,re_img)) # horizontal
v=np.vstack((re_img,re_img))# do bar Re_img lia hai so 2 baar hii aayega
cv2.imshow("MEOW",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
# hor. andver. dono ko mergee karna hai then
img=cv2.imread(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\img1.jpg")
re_img=cv2.resize(img,(300,300))
h=np.hstack((re_img,re_img)) # horizontal
v=np.vstack((h,h,h))
cv2.imshow("MEOW",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

SLIDESHOW

In [22]:
import os
# For slideshow ek seperate folder ko banana hoga 

In [23]:
list_name=os.listdir(r"C:\Users\Asus\openCV\Show Multiple img and Slide Show\Slide show")
list_name

['img1.jpg', 'img2.jpg', 'img3.jpg']

In [26]:
for name in list_name:
    path='C:\\Users\\Asus\\openCV\\Show Multiple img and Slide Show\\Slide show'
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    img=cv2.resize(img,(500,600))
    cv2.imshow("MEOW",img)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()